### ISSUE TITLE
Does not build with fixed-vector 0.7.0.0

### ISSUE THREAD

**Issue by idontgetoutmuch** [leventov/yarr#3]
If you recall, I managed to get yarr to build under 7.8.3. That’s the good news.

I then tried to get it included in stackage. Quite reasonably Michael Snoyman tells me that I need to use the latest version of fixed-vector (0.7.0.0). yarr currently specifies 0.1.2.1.

I changed the constraint in the .cabal file to >= 0.7.0.0 && < 0.8.0.0 and got compilation errors (not surprisingly).

1. Data.Vector.Fixed.Internal has disappeared but I found the functions required from it in different modules.

    import Data.Vector.Fixed.Mutable ( inspectVec )
    import Data.Vector.Fixed.Cont ( accum )

I think this should be ok.

2. There is no longer a constructor called VecList.

    Data/Yarr/Utils/FixedVector/InlinableArity.hs:39:26:
        Not in scope: data constructor ‘VecList’
        In the Template Haskell quotation
          [| convert $ VecList ($(listE vs)) |]

The source for the full module is here: https://github.com/leventov/yarr/blob/master/yarr/Data/Yarr/Utils/FixedVector/InlinableArity.hs

It’s not clear to me how to fix this without affecting performance. There are now constructors Nil and Cons.

    data VecList n a where
      Nil  :: VecList Z a
      Cons :: a -> VecList n a -> VecList (S n) a
      deriving (Typeable)

Do you have any suggestions on what I should do?

**Comment by idontgetoutmuch** [comment]
Thanks to @leventov and @Shimuuar this now compiles with ghc 7.8.3 and fixed-vector 0.7.0.0.
